<a href="https://colab.research.google.com/github/ssb60386-beep/AI-LAB/blob/main/lab02(task2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Crop_recommendation.csv to Crop_recommendation.csv

In [3]:
df = pd.read_csv("Crop_recommendation.csv")

print("Dataset loaded successfully!")
print("Number of records:", len(df))
print("Number of columns:", len(df.columns))

Dataset loaded successfully!
Number of records: 2200
Number of columns: 8

In [4]:
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [5]:
print("Dataset Information:")
print(df.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB
None

In [6]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [7]:
features = [
    "N",
    "P",
    "K",
    "temperature",
    "humidity",
    "ph",
    "rainfall"
]

print("Selected Features:")
for feature in features:
    print(feature)

Selected Features:
N
P
K
temperature
humidity
ph
rainfall

In [8]:
print("Minimum and Maximum Values:")
print(df[features].agg(["min", "max"]))

Minimum and Maximum Values:
       N    P    K  temperature   humidity        ph    rainfall
min    0    5    5     8.825675  14.258040  3.504752   20.211267
max  140  145  205    43.675493  99.981876  9.935091  298.560117

In [9]:
def crop_decision(N, P, K, temperature, humidity, ph, rainfall):

    score = 0

    # Nitrogen condition
    if N >= 40:
        score += 1
    elif N >= 20:
        score += 0.5
    else:
        score += 0

    # Phosphorus condition
    if P >= 30:
        score += 1
    elif P >= 15:
        score += 0.5

    # Potassium condition
    if K >= 30:
        score += 1
    elif K >= 15:
        score += 0.5

    # Temperature condition
    if 20 <= temperature <= 30:
        score += 1
    elif 15 <= temperature <= 35:
        score += 0.5

    # Humidity condition
    if 50 <= humidity <= 80:
        score += 1
    elif 40 <= humidity <= 90:
        score += 0.5

    # pH condition
    if 5.5 <= ph <= 7.5:
        score += 1
    elif 5.0 <= ph <= 8.0:
        score += 0.5

    # Rainfall condition
    if 80 <= rainfall <= 250:
        score += 1
    elif 50 <= rainfall <= 300:
        score += 0.5

    # Final decision
    if score >= 5:
        decision = "Highly Suitable"
    elif score >= 3:
        decision = "Moderately Suitable"
    else:
        decision = "Less Suitable"

    return decision

In [10]:
decision = crop_decision(
    90,      # N
    42,      # P
    43,      # K
    25.5,    # Temperature
    70,      # Humidity
    6.5,     # pH
    180      # Rainfall
)

print("Agricultural Decision:", decision)

Agricultural Decision: Highly Suitable

In [11]:
decisions = []

for index, row in df.iterrows():

    decision = crop_decision(
        row["N"],
        row["P"],
        row["K"],
        row["temperature"],
        row["humidity"],
        row["ph"],
        row["rainfall"]
    )

    decisions.append(decision)

df["rule_decision"] = decisions

print("Rule-based decisions generated successfully!")

Rule-based decisions generated successfully!

In [12]:
result = df[
    [
        "N",
        "P",
        "K",
        "temperature",
        "humidity",
        "ph",
        "rainfall",
        "label",
        "rule_decision"
    ]
].head(10)

print(result.to_string(index=False))

 N  P  K  temperature  humidity       ph   rainfall label   rule_decision
90 42 43    20.879744 82.002744 6.502985 202.935536  rice Highly Suitable
85 58 41    21.770462 80.319644 7.038096 226.655537  rice Highly Suitable
60 55 44    23.004459 82.320763 7.840207 263.964248  rice Highly Suitable
74 35 40    26.491096 80.158363 6.980401 242.864034  rice Highly Suitable
78 42 42    20.130175 81.604873 7.628473 262.717340  rice Highly Suitable
69 37 42    23.058049 83.370118 7.073454 251.055000  rice Highly Suitable
69 55 38    22.708838 82.639414 5.700806 271.324860  rice Highly Suitable
94 53 40    20.277744 82.894086 5.718627 241.974195  rice Highly Suitable
89 54 38    24.515881 83.535216 6.685346 230.446236  rice Highly Suitable
68 58 38    23.223974 83.033227 6.336254 221.209196  rice Highly Suitable

In [13]:
def recommend_crop(N, P, K, temperature, humidity, ph, rainfall):

    # Rice-like conditions
    if (
        humidity >= 70
        and rainfall >= 150
        and temperature >= 20
        and ph >= 5.0
        and ph <= 7.5
    ):
        return "rice"

    # Maize-like conditions
    elif (
        temperature >= 20
        and temperature <= 30
        and rainfall >= 60
        and rainfall <= 150
        and humidity >= 50
    ):
        return "maize"

    # Chickpea-like conditions
    elif (
        temperature >= 15
        and temperature <= 30
        and rainfall < 100
        and ph >= 6
        and ph <= 8
    ):
        return "chickpea"

    # Cotton-like conditions
    elif (
        temperature >= 25
        and humidity >= 50
        and rainfall >= 50
        and rainfall <= 150
    ):
        return "cotton"

    # Generic vegetable category
    elif (
        temperature >= 18
        and temperature <= 30
        and ph >= 5.5
        and ph <= 7.5
    ):
        return "vegetable"

    else:
        return "general crop"

In [14]:
crop_predictions = []

for index, row in df.iterrows():

    prediction = recommend_crop(
        row["N"],
        row["P"],
        row["K"],
        row["temperature"],
        row["humidity"],
        row["ph"],
        row["rainfall"]
    )

    crop_predictions.append(prediction)

df["rule_crop"] = crop_predictions

In [15]:
comparison = df[
    [
        "N",
        "P",
        "K",
        "temperature",
        "humidity",
        "ph",
        "rainfall",
        "label",
        "rule_crop"
    ]
].head(10)

print(comparison.to_string(index=False))

 N  P  K  temperature  humidity       ph   rainfall label    rule_crop
90 42 43    20.879744 82.002744 6.502985 202.935536  rice         rice
85 58 41    21.770462 80.319644 7.038096 226.655537  rice         rice
60 55 44    23.004459 82.320763 7.840207 263.964248  rice general crop
74 35 40    26.491096 80.158363 6.980401 242.864034  rice         rice
78 42 42    20.130175 81.604873 7.628473 262.717340  rice general crop
69 37 42    23.058049 83.370118 7.073454 251.055000  rice         rice
69 55 38    22.708838 82.639414 5.700806 271.324860  rice         rice
94 53 40    20.277744 82.894086 5.718627 241.974195  rice         rice
89 54 38    24.515881 83.535216 6.685346 230.446236  rice         rice
68 58 38    23.223974 83.033227 6.336254 221.209196  rice         rice

In [16]:
matches = 0

for actual, predicted in zip(df["label"], df["rule_crop"]):

    if actual == predicted:
        matches += 1

total_records = len(df)

matching_percentage = (matches / total_records) * 100

print("Total Records:", total_records)
print("Matching Decisions:", matches)
print("Non-Matching Decisions:", total_records - matches)
print("Matching Percentage:", round(matching_percentage, 2), "%")

Total Records: 2200
Matching Decisions: 241
Non-Matching Decisions: 1959
Matching Percentage: 10.95 %

In [17]:
first_10 = df.head(10)

matches_10 = 0

for actual, predicted in zip(
    first_10["label"],
    first_10["rule_crop"]
):

    if actual == predicted:
        matches_10 += 1

percentage_10 = (matches_10 / 10) * 100

print("Evaluation of First 10 Records")
print("-------------------------------")
print("Total Records:", 10)
print("Matching Decisions:", matches_10)
print("Incorrect Decisions:", 10 - matches_10)
print("Matching Percentage:", percentage_10, "%")

Evaluation of First 10 Records
-------------------------------
Total Records: 10
Matching Decisions: 8
Incorrect Decisions: 2
Matching Percentage: 80.0 %

In [18]:
category_counts = df["rule_decision"].value_counts()

print("Agricultural Decision Categories:")
print(category_counts)

Agricultural Decision Categories:
rule_decision
Highly Suitable        1352
Moderately Suitable     824
Less Suitable            24
Name: count, dtype: int64

In [19]:
final_result = df[
    [
        "N",
        "P",
        "K",
        "temperature",
        "humidity",
        "ph",
        "rainfall",
        "label",
        "rule_decision",
        "rule_crop"
    ]
].head(10)

final_result

,N,P,K,temperature,humidity,ph,rainfall,label,rule_decision,rule_crop
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice,Highly Suitable,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice,Highly Suitable,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice,Highly Suitable,general crop
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice,Highly Suitable,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice,Highly Suitable,general crop
5,69,37,42,23.058049,83.370118,7.073454,251.055000,rice,Highly Suitable,rice
6,69,55,38,22.708838,82.639414,5.700806,271.324860,rice,Highly Suitable,rice
7,94,53,40,20.277744,82.894086,5.718627,241.974195,rice,Highly Suitable,rice
8,89,54,38,24.515881,83.535216,6.685346,230.446236,rice,Highly Suitable,rice
9,68,58,38,23.223974,83.033227,6.336254,221.209196,rice,Highly Suitable,rice

In [20]:
crop_patterns = df.groupby("label")[
    [
        "N",
        "P",
        "K",
        "temperature",
        "humidity",
        "ph",
        "rainfall"
    ]
].mean()

print(crop_patterns.round(2))

                  N       P       K  temperature  humidity    ph  rainfall
label
apple         20.80  134.22  199.89        22.63     92.33  5.93    112.65
banana       100.23   82.01   50.05        27.38     80.36  5.98    104.63
blackgram     40.02   67.47   19.24        29.97     65.12  7.13     67.88
chickpea      40.09   67.79   79.92        18.87     16.86  7.34     80.06
coconut       21.98   16.93   30.59        27.41     94.84  5.98    175.69
coffee       101.20   28.74   29.94        25.54     58.87  6.79    158.07
cotton       117.77   46.24   19.56        23.99     79.84  6.91     80.40
grapes        23.18  132.53  200.11        23.85     81.88  6.03     69.61
jute          78.40   46.86   39.99        24.96     79.64  6.73    174.79
kidneybeans   20.75   67.54   20.05        20.12     21.61  5.75    105.92
lentil        18.77   68.36   19.41        24.51     64.80  6.93     45.68
maize         77.76   48.44   19.79        22.39     65.09  6.25     84.77
mango         20.07   27.18   29.92        31.21     50.16  5.77     94.70
mothbeans     21.44   48.01   20.23        28.19     53.16  6.83     51.20
mungbean      20.99   47.28   19.87        28.53     85.50  6.72     48.40
muskmelon    100.32   17.72   50.08        28.66     92.34  6.36     24.69
orange        19.58   16.55   10.01        22.77     92.17  7.02    110.47
papaya        49.88   59.05   50.04        33.72     92.40  6.74    142.63
pigeonpeas    20.73   67.73   20.29        27.74     48.06  5.79    149.46
pomegranate   18.87   18.75   40.21        21.84     90.13  6.43    107.53
rice          79.89   47.58   39.87        23.69     82.27  6.43    236.18
watermelon    99.42   17.00   50.22        25.59     85.16  6.50     50.79

In [21]:
rice_data = df[df["label"] == "rice"]

print("Average conditions for rice:")
print(rice_data[
    [
        "N",
        "P",
        "K",
        "temperature",
        "humidity",
        "ph",
        "rainfall"
    ]
].mean().round(2))

Average conditions for rice:
N               79.89
P               47.58
K               39.87
temperature     23.69
humidity        82.27
ph               6.43
rainfall       236.18
dtype: float64

In [22]:
sample = df.iloc[0]

print("Selected Record:")
print(sample[
    [
        "N",
        "P",
        "K",
        "temperature",
        "humidity",
        "ph",
        "rainfall"
    ]
])

print("\nActual Crop:", sample["label"])
print("Rule-Based Crop:", sample["rule_crop"])
print("Suitability:", sample["rule_decision"])

Selected Record:
N                      90
P                      42
K                      43
temperature     20.879744
humidity        82.002744
ph               6.502985
rainfall       202.935536
Name: 0, dtype: object

Actual Crop: rice
Rule-Based Crop: rice
Suitability: Highly Suitable

In [23]:
crop_means = df.groupby("label")[
    [
        "N",
        "P",
        "K",
        "temperature",
        "humidity",
        "ph",
        "rainfall"
    ]
].mean()


def data_driven_crop_recommendation(
    N, P, K, temperature, humidity, ph, rainfall
):

    input_values = np.array([
        N,
        P,
        K,
        temperature,
        humidity,
        ph,
        rainfall
    ])

    best_crop = None
    smallest_distance = float("inf")

    for crop in crop_means.index:

        crop_values = crop_means.loc[crop].values

        distance = np.sqrt(
            np.sum((input_values - crop_values) ** 2)
        )

        if distance < smallest_distance:
            smallest_distance = distance
            best_crop = crop

    return best_crop

In [24]:
sample = df.iloc[0]

recommendation = data_driven_crop_recommendation(
    sample["N"],
    sample["P"],
    sample["K"],
    sample["temperature"],
    sample["humidity"],
    sample["ph"],
    sample["rainfall"]
)

print("Actual Crop:", sample["label"])
print("Recommended Crop:", recommendation)

Actual Crop: rice
Recommended Crop: jute

In [25]:
data_driven_predictions = []

for index, row in df.head(10).iterrows():

    prediction = data_driven_crop_recommendation(
        row["N"],
        row["P"],
        row["K"],
        row["temperature"],
        row["humidity"],
        row["ph"],
        row["rainfall"]
    )

    data_driven_predictions.append(prediction)

df.loc[df.index[:10], "data_driven_crop"] = data_driven_predictions

print(
    df[
        ["label", "data_driven_crop"]
    ].head(10).to_string(index=False)
)

label data_driven_crop
 rice             jute
 rice             rice
 rice             rice
 rice             rice
 rice             rice
 rice             rice
 rice             rice
 rice             rice
 rice             rice
 rice             rice

In [26]:
matches = 0

for actual, predicted in zip(
    df["label"].head(10),
    df["data_driven_crop"].head(10)
):

    if actual == predicted:
        matches += 1

accuracy = (matches / 10) * 100

print("Total Records:", 10)
print("Correct Predictions:", matches)
print("Incorrect Predictions:", 10 - matches)
print("Matching Percentage:", round(accuracy, 2), "%")

Total Records: 10
Correct Predictions: 9
Incorrect Predictions: 1
Matching Percentage: 90.0 %

In [27]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("Crop_recommendation.csv")

print("Dataset loaded successfully!")
print("Total records:", len(df))

# Selected features
features = [
    "N",
    "P",
    "K",
    "temperature",
    "humidity",
    "ph",
    "rainfall"
]

print("\nSelected Features:")
for feature in features:
    print(feature)


# Rule-based agricultural suitability function
def crop_decision(N, P, K, temperature, humidity, ph, rainfall):

    score = 0

    if N >= 40:
        score += 1
    elif N >= 20:
        score += 0.5

    if P >= 30:
        score += 1
    elif P >= 15:
        score += 0.5

    if K >= 30:
        score += 1
    elif K >= 15:
        score += 0.5

    if 20 <= temperature <= 30:
        score += 1
    elif 15 <= temperature <= 35:
        score += 0.5

    if 50 <= humidity <= 80:
        score += 1
    elif 40 <= humidity <= 90:
        score += 0.5

    if 5.5 <= ph <= 7.5:
        score += 1
    elif 5.0 <= ph <= 8.0:
        score += 0.5

    if 80 <= rainfall <= 250:
        score += 1
    elif 50 <= rainfall <= 300:
        score += 0.5

    if score >= 5:
        return "Highly Suitable"
    elif score >= 3:
        return "Moderately Suitable"
    else:
        return "Less Suitable"


# Process dataset records
decisions = []

for index, row in df.iterrows():

    decision = crop_decision(
        row["N"],
        row["P"],
        row["K"],
        row["temperature"],
        row["humidity"],
        row["ph"],
        row["rainfall"]
    )

    decisions.append(decision)

df["rule_decision"] = decisions


# Display first 10 results
print("\nFirst 10 Results:")
print(
    df[
        [
            "N",
            "P",
            "K",
            "temperature",
            "humidity",
            "ph",
            "rainfall",
            "label",
            "rule_decision"
        ]
    ].head(10).to_string(index=False)
)


# Count categories
print("\nDecision Category Counts:")
print(df["rule_decision"].value_counts())


# Dataset pattern analysis
print("\nAverage Conditions for Each Crop:")
print(
    df.groupby("label")[features]
    .mean()
    .round(2)
)

Dataset loaded successfully!
Total records: 2200

Selected Features:
N
P
K
temperature
humidity
ph
rainfall

First 10 Results:
 N  P  K  temperature  humidity       ph   rainfall label   rule_decision
90 42 43    20.879744 82.002744 6.502985 202.935536  rice Highly Suitable
85 58 41    21.770462 80.319644 7.038096 226.655537  rice Highly Suitable
60 55 44    23.004459 82.320763 7.840207 263.964248  rice Highly Suitable
74 35 40    26.491096 80.158363 6.980401 242.864034  rice Highly Suitable
78 42 42    20.130175 81.604873 7.628473 262.717340  rice Highly Suitable
69 37 42    23.058049 83.370118 7.073454 251.055000  rice Highly Suitable
69 55 38    22.708838 82.639414 5.700806 271.324860  rice Highly Suitable
94 53 40    20.277744 82.894086 5.718627 241.974195  rice Highly Suitable
89 54 38    24.515881 83.535216 6.685346 230.446236  rice Highly Suitable
68 58 38    23.223974 83.033227 6.336254 221.209196  rice Highly Suitable

Decision Category Counts:
rule_decision
Highly Suitable        1352
Moderately Suitable     824
Less Suitable            24
Name: count, dtype: int64

Average Conditions for Each Crop:
                  N       P       K  temperature  humidity    ph  rainfall
label
apple         20.80  134.22  199.89        22.63     92.33  5.93    112.65
banana       100.23   82.01   50.05        27.38     80.36  5.98    104.63
blackgram     40.02   67.47   19.24        29.97     65.12  7.13     67.88
chickpea      40.09   67.79   79.92        18.87     16.86  7.34     80.06
coconut       21.98   16.93   30.59        27.41     94.84  5.98    175.69
coffee       101.20   28.74   29.94        25.54     58.87  6.79    158.07
cotton       117.77   46.24   19.56        23.99     79.84  6.91     80.40
grapes        23.18  132.53  200.11        23.85     81.88  6.03     69.61
jute          78.40   46.86   39.99        24.96     79.64  6.73    174.79
kidneybeans   20.75   67.54   20.05        20.12     21.61  5.75    105.92
lentil        18.77   68.36   19.41        24.51     64.80  6.93     45.68
maize         77.76   48.44   19.79        22.39     65.09  6.25     84.77
mango         20.07   27.18   29.92        31.21     50.16  5.77     94.70
mothbeans     21.44   48.01   20.23        28.19     53.16  6.83     51.20
mungbean      20.99   47.28   19.87        28.53     85.50  6.72     48.40
muskmelon    100.32   17.72   50.08        28.66     92.34  6.36     24.69
orange        19.58   16.55   10.01        22.77     92.17  7.02    110.47
papaya        49.88   59.05   50.04        33.72     92.40  6.74    142.63
pigeonpeas    20.73   67.73   20.29        27.74     48.06  5.79    149.46
pomegranate   18.87   18.75   40.21        21.84     90.13  6.43    107.53
rice          79.89   47.58   39.87        23.69     82.27  6.43    236.18
watermelon    99.42   17.00   50.22        25.59     85.16  6.50     50.79